ERROR - 2023-06-20 13:59:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#10 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-20 13:59:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `apprenant`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 13:59:10 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php:10
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php(10): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
in APPPATH\Views\errors\html\production.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-06-20 13:59:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#10 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-20 13:59:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `apprenant`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 13:59:22 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php:10
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php(10): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
in APPPATH\Views\errors\html\production.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-06-20 14:00:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#10 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-20 14:00:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `apprenant`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:00:34 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php:10
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php(10): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
in APPPATH\Views\errors\html\production.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-06-20 14:00:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#10 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-20 14:00:35 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `apprenant`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:00:35 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php:10
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php(10): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
in APPPATH\Views\errors\html\production.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-06-20 14:00:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#10 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-20 14:00:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `apprenant`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:00:36 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php:10
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php(10): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
in APPPATH\Views\errors\html\production.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-06-20 14:02:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#10 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-20 14:02:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `apprenant`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:02:23 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php:10
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php(10): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
in APPPATH\Views\errors\html\production.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-06-20 14:06:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#10 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-20 14:06:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `apprenant`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:06:16 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php:10
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php(10): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
in APPPATH\Views\errors\html\production.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-06-20 14:17:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#10 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-20 14:17:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `apprenant`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:17:12 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php:10
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php(10): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
in APPPATH\Views\errors\html\production.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-06-20 14:29:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#10 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\kakofor\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#9 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-20 14:29:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `apprenant`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:29:29 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php:10
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\production.php(10): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4\kakofor\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4\kakofor\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4\kakofor\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci4\kakofor\app\Models\ApprenantModel.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(14): App\Models\ApprenantModel->getApprenant()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#8 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
in APPPATH\Views\errors\html\production.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-06-20 14:33:12 --> Undefined array key "nom"
in APPPATH\Views\apprenant\index.php on line 7.
 1 APPPATH\Views\apprenant\index.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nom"', 'C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\index.php', 7)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('apprenant/index', [], true)
 5 APPPATH\Controllers\Apprenant.php(19): view('apprenant/index')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:33:12 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\error_exception.php:15
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 15)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\error_exception.php(15): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(ErrorException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#6 {main}
  thrown
【Previous Exception】
ErrorException
Undefined array key "nom"
#0 C:\xampp\htdocs\ci4\kakofor\app\Views\apprenant\index.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 7)
#1 C:\xampp\htdocs\ci4\kakofor\system\View\View.php(213): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4\kakofor\system\Common.php(1184): CodeIgniter\View\View->render('apprenant/index', Array, true)
#4 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(19): view('apprenant/index')
#5 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
in APPPATH\Views\errors\html\error_exception.php on line 15.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-06-20 14:33:17 --> Undefined array key "nom"
in APPPATH\Views\apprenant\index.php on line 7.
 1 APPPATH\Views\apprenant\index.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nom"', 'C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\index.php', 7)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('apprenant/index', [], true)
 5 APPPATH\Controllers\Apprenant.php(19): view('apprenant/index')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:33:17 --> Uncaught ErrorException: file_get_contents(C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\debug.css): Failed to open stream: No such file or directory in C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\error_exception.php:15
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 15)
#1 C:\xampp\htdocs\ci4\kakofor\app\Views\errors\html\error_exception.php(15): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(282): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(285): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4\kakofor\system\Debug\Exceptions.php(156): CodeIgniter\Debug\Exceptions->render(Object(ErrorException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#6 {main}
  thrown
【Previous Exception】
ErrorException
Undefined array key "nom"
#0 C:\xampp\htdocs\ci4\kakofor\app\Views\apprenant\index.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 7)
#1 C:\xampp\htdocs\ci4\kakofor\system\View\View.php(213): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4\kakofor\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4\kakofor\system\Common.php(1184): CodeIgniter\View\View->render('apprenant/index', Array, true)
#4 C:\xampp\htdocs\ci4\kakofor\app\Controllers\Apprenant.php(19): view('apprenant/index')
#5 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(934): App\Controllers\Apprenant->index()
#6 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
#7 C:\xampp\htdocs\ci4\kakofor\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\kakofor\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
in APPPATH\Views\errors\html\error_exception.php on line 15.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-06-20 14:40:08 --> Undefined array key "nom"
in APPPATH\Views\apprenant\index.php on line 7.
 1 APPPATH\Views\apprenant\index.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nom"', 'C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\index.php', 7)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('apprenant/index', [], true)
 5 APPPATH\Controllers\Apprenant.php(19): view('apprenant/index')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:42:38 --> Undefined array key "nom"
in APPPATH\Views\apprenant\view.php on line 1.
 1 APPPATH\Views\apprenant\view.php(1): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nom"', 'C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\view.php', 1)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\view.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('apprenant/view', [], true)
 5 APPPATH\Controllers\Apprenant.php(32): view('apprenant/view')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->view('1')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:47:20 --> Undefined variable $apprenant_item
in APPPATH\Views\apprenant\view.php on line 4.
 1 APPPATH\Views\apprenant\view.php(4): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $apprenant_item', 'C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\view.php', 4)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\view.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('apprenant/view', [], true)
 5 APPPATH\Controllers\Apprenant.php(32): view('apprenant/view')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->view('1')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 14:48:07 --> Undefined variable $apprenant_item
in APPPATH\Views\apprenant\view.php on line 4.
 1 APPPATH\Views\apprenant\view.php(4): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $apprenant_item', 'C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\view.php', 4)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\apprenant\\view.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('apprenant/view', [], true)
 5 APPPATH\Controllers\Apprenant.php(32): view('apprenant/view')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Apprenant->view('1')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Apprenant))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:27:50 --> Class "App\Models\FormationModel" not found
in APPPATH\Controllers\Formation.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:29:43 --> Class "App\Models\FormationModel" not found
in APPPATH\Controllers\Formation.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:29:47 --> Class "App\Models\FormationModel" not found
in APPPATH\Controllers\Formation.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:31:19 --> Class "App\Models\FormationModel" not found
in APPPATH\Controllers\Formation.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:35:27 --> Class "App\Controllers\App\Controllers\FormationModel" not found
in APPPATH\Controllers\Formation.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:38:38 --> Class "App\Models\FormationModel" not found
in APPPATH\Controllers\Formation.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:40:58 --> Undefined variable $model
in APPPATH\Controllers\Formation.php on line 13.
 1 APPPATH\Controllers\Formation.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $model', 'C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Controllers\\Formation.php', 13)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:41:00 --> Undefined variable $model
in APPPATH\Controllers\Formation.php on line 13.
 1 APPPATH\Controllers\Formation.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $model', 'C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Controllers\\Formation.php', 13)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:42:58 --> Class "App\Models\FormationModel" not found
in APPPATH\Controllers\Formation.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:45:48 --> Class "App\Models\FormationModel" not found
in APPPATH\Controllers\Formation.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-20 15:49:47 --> Undefined variable $apprenant_item
in APPPATH\Views\formation\index.php on line 14.
 1 APPPATH\Views\formation\index.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $apprenant_item', 'C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\formation\\index.php', 14)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\ci4\\kakofor\\app\\Views\\formation\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('formation/index', [], true)
 5 APPPATH\Controllers\Formation.php(19): view('formation/index')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Formation->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formation))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
